### ISSUE TITLE
Customize popup style

### ISSUE THREAD

**Issue by speedfl** [ronzeidman/ng2-ui-auth#100]
Hello,

I am using method authenticate to open the dialog Facebook or Linkedin

Is there any way to specify the option for the popup open like:
```location=<yes/no>,toolbar=<yes/no>,width=<some width>,height=<some height>```

**Comment by ronzeidman** [comment]
You can customize size and location (popupOptions): https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/config.service.ts

But why would you want a toolbar?

**Comment by speedfl** [comment]
Hello.

Thanks for your answer. In fact I am using it with ionic project. It is launched with inappbrowser. And there is by default the location and the toolbar. So I don't want to add it but to remove it :)

**Comment by ronzeidman** [comment]
Maybe @royipressburger can help? I don't have experience in ionic.

**Comment by royipressburger** [comment]
From what I know what you are asking has nothing to do with this repository.
Since the popup opens with the in app browser plugin you should look for a way to style it from the plugin itself.. I have no idea how to do that.

In any case a better solution (just for facebook, not sure about LinkedIn) is to use native login. (A click on a facebook login will open facebook app)

**Comment by speedfl** [comment]
I know that for customization I have to modify the plugin itself however set location=no is part of the opening popup to display the location bar. And inappbrowser is also based on this option. Anyway i will check for native login for facebook.
Thanks

**Comment by ronzeidman** [comment]
Added `visibleToolbar` to the IPopupOptions so you can now set it manually. in addition I've added `toolbar=no` as default behavior so if it works you don't have to do anything except upgrade to version 7.0.1

**Comment by speedfl** [comment]
Thanks a lot :)
