### ISSUE TITLE
Fix for JwtHttp class

### ISSUE THREAD

**Issue by aslubsky** [ronzeidman/ng2-ui-auth#11]
Hi, this is fix for JwtHttp class, when your url var it not a String objects

```javascript
if (url instanceof Request) {
	url.headers = url.headers || new Headers();
	url.headers.set(this._config.authHeader, this._config.authToken + ' ' + this._shared.getToken());
} else {
	options.headers = options.headers || new Headers();
	options.headers.set(this._config.authHeader, this._config.authToken + ' ' + this._shared.getToken());
}
```
like here

```javascript
return this.jwtHttp.request(new Request({
	method: RequestMethod.Get,
	url: '/api',
	search: this._getUrlParams(params)
})).toPromise();
```
I do not make a "Pull Request" because my fork https://github.com/davintoo/ng2-ui-auth was heavily modified

**Comment by ronzeidman** [comment]
Thanks, I will integrate soon.
What other fixes you've added to your fork anything generic I can also add to my branch?

**Comment by aslubsky** [comment]
No more fixes, just change build (from src to dist) and replace token separator in locals storage from '_' to '-' (I need this fix for backward compatible with existing project)

**Comment by ronzeidman** [comment]
I've committed a fix for a modifiable token separator `NG2_UI_AUTH_PROVIDERS({ tokenSeparator: '-', providers: {google: {clientId: GOOGLE_CLIENT_ID}}})`
and also in the latest version everything is bundled (and minified if you want) to the dist folder using commonjs module.
So, I'd appreciate if you try and use directly the master branch and tell me if everything works fine. When you approve I'll bump the npm version.
If you won't I'll probably test it myself and bump the version tomorrow.

Thanks!

**Comment by ronzeidman** [comment]
to compile my version run:
```
npm install
npm run typings
npm run compile
npm run bundle
```

**Comment by aslubsky** [comment]
Cool, I'll try to update it today. Thanks

**Comment by aslubsky** [comment]
1) The package zone.js@0.5.10 does not satisfy its siblings' peerDependencies requirements! The package zone.js@0.5.10 does not satisfy its siblings' peerDependencies requirements!
2) Please add tokenSeparator to ICustomConfig interface
3) local.ts file, method login
```
opts.headers = new Headers({
   'Content-Type': 'application/json'
});
```
I need this code, my backend read only json. May be make it optional ?
Same problem on oauth2.ts method exchangeForToken, in this request I need json format to

**Comment by ronzeidman** [comment]
try now `NG2_UI_AUTH_PROVIDERS({ tokenSeparator: '-', defaultHeaders: {'Content-Type': 'application/json'}, providers: {google: {clientId: GOOGLE_CLIENT_ID}}})`

also removed JWT_HTTP_PROVIDER, JwtHttp is provided in the default provider now and all other classes use the JwtHttp instead of the plain Http.

**Comment by aslubsky** [comment]
I've added defaultHeaders to Http requests to, please merge pull request

**Comment by ronzeidman** [comment]
since I've made JwtHttp a dependency of Oauth, Local etc. the default headers should have been provided out of the JwtHttp box:
provide(Local, { useFactory: (http, shared, providedConfig) => { return new Local(http, shared, providedConfig);}, deps: [**JwtHttp**, Shared, Config]} ),

it didn't work? somehow the plain Http got injected?

**Comment by aslubsky** [comment]
https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/local.ts
but in Local class constructor You use 
```
private http: Http,
```
not **JwtHttp**, so in login method **this.http.request** don't send any headers. Or am I wrong?

**Comment by ronzeidman** [comment]
When I provide the Local class now I use a factory (not the default injector) the provider should explicitly provide the right class. And since JwtHttp inherits from Http the constructor has no trouble getting an Http object:
When I use this line:
```typescript
provide(Local, { useFactory: (http, shared, providedConfig) => { return new Local(http, shared, providedConfig);}, deps: [JwtHttp, Shared, Config]} )
```
If  constructor that tries to get a "Local" class it automatically creates the local class with the factory provided by the provider.

**Comment by aslubsky** [comment]
Sorry, works fine, You can remove my pull request. Thanks!

**Comment by ronzeidman** [comment]
Great! Thanks for suggesting improvements and verifying this fix!

**Comment by aslubsky** [comment]
No problem. Cheers!
