### ISSUE TITLE
Unable to upload files using JwtHttp

### ISSUE THREAD

**Issue by nimbusparis** [ronzeidman/ng2-ui-auth#115]
While trying to upload files using JwtHttp, this was not working. 
My Api had the following prototype (C#):
`[HttpPut("AddPictures/{gameId}")]
    public IActionResult AddImageNodes(int gameId, List<IFormFile> files)`
It work like a charm sending files using PostMan.

When using `JwtHttp.put` function to send data to the api, it was called but the the parameter `files` is empty. Using `Http` object fix the problem:

     upload(files: File[], gameId) {
        let headers = new Headers();
        headers.delete('Content-Type');
        const formData = new FormData();
        for (var file of files) {
           formData.append("files", file);
        }
        let options = new RequestOptions({ headers: headers });
        return this.http.put(`api/game/AddPictures/${gameId}`, formData, options);
    }

**Comment by ronzeidman** [comment]
There were many issues with the JwtHttp implementation, and since Http is deprecated in Angular 5.0.0 I've removed it from the new version. Now, this library only has a basic HttpClient interceptor that adds an authorization header if it's missing and you are authenticated.
If you are using angular 5 you can try the beta: `npm i ng2-ui-auth@8.0.0-beta.2` 
I'm closing this for now if you are still experiencing problems tell me and I'll reopen it.
