### ISSUE TITLE
Scope parameter in the request's body

### ISSUE THREAD

**Issue by jpeisenbarth** [ronzeidman/ng2-ui-auth#136]
Hello,

first of all thank you for this library !

I noticed that in the new version 8 the scope field in the request's body isn't an array anymore, now it's a string containing all the scopes separated with spaces ( "scope": "openid profile email" instead of "scope": ["openid","profile","email"] ).

I think it comes from this file https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/oauth2.service.ts#L42 where `authorizationData` contains formatted values by `getAuthorizationData`.

The CHANGELOG.md does not mention anything about this change, did I missed something or is it a bug ?

Thank you in advance

**Comment by ronzeidman** [comment]
`scope` is still an array (see example: https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/config.service.ts#L158)
What is different is what is sent to your server. instead of a mashup of several properties from what you receive from the authorization endpoint, specific properties from your config, and user data. You are sending a predictable object which consists of the thing you actually sent to the authorization endpoint (which includes the scope joint with it's configured delimiter) and the authorization endpoint's response in a separate property.
This looked to me a much better and understandable way to know what your server will actually receive. I understand that specifically, the scope variable would be easier to handle in its original array form but in my opinion, it was a small price to pay for consistency (in the satellizer library some fields were as they were configured in the config, some resolved and some were missing...).
If you have an elegant suggestion how to make it more usable I'm open to hearing about it. I guess if there is a larger demand for the scope variable to specifically be sent as an array I could change it... just thoughts...

**Comment by jpeisenbarth** [comment]
OK, I see your point. I think you're right it's a better way to handle the parameters.

By the way, the server doesn't need to handle the scope parameter received from the client since the provider (github, google, etc) already received the scopes in the initial request from the client and the user already authorized the OAuth app, right ?

**Comment by ronzeidman** [comment]
The server can behave differently if different scopes were asked depending on your internal logic. Maybe if a user gave you permission to post on his behalf you would want to do that and if not you will not even attempt to do so. So the information is useful but not necessary.
