### ISSUE TITLE
Possible error in extend() function

### ISSUE THREAD

**Issue by vadag** [ronzeidman/ng2-ui-auth#29]
Hello! I believe that in https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/utils.ts#L8 should be 
`dst[key] = src[key]`.

**Comment by ronzeidman** [comment]
How did it work I wonder... Thanks for pointing it out

**Comment by ronzeidman** [comment]
Fixed it, bumped to version 3.2.0. It affects custom provider options and custom popup sizes.
If typescript supported the spread operator it would have been replaced by it, maybe I should have replaced it by an `Object.assign` polyfill but it would have been too intrusive.
Anyway thanks.

**Comment by vadag** [comment]
Thank you!

**Comment by vadag** [comment]
well, "while it works - don't touch it" as we say here in Russia. I think your code is pretty good until it do what it should to do. May be later I'll make couple of PR's, but it's another story :)

**Comment by ronzeidman** [comment]
That's always the case 😉. Open issues before PRs, I'd like to know what's not working, I've made/converted this library for personal use so any use other than my own is to be tested by the community... I probably have to write tests, but for that I will probably have to create some fake public developer accounts at Google/Facebook/Twitter and because of the pop-up -> click nature of oauth it will probably not be fully automated... if you can think a way to automatically test the library, I'm open to suggestions.

Thanks again for pointing out bugs

**Comment by ronzeidman** [comment]
@vadag I think I've fixed all the errors it caused, can you test?
