### ISSUE TITLE
Oauth1 configuration values are all null

### ISSUE THREAD

**Issue by sunild** [ronzeidman/ng2-ui-auth#30]
[Line 26](https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/oauth1.ts#L26) in Oauth1 sets all the configuration values to `null` because it is copying the values from an object that has all null values.

So regardless of what I pass in as options (for Twitter), they are all null so authenticating doesn't work.

I'd submit a PR but am still getting familiar w/the code :) I assume that somehow the Oauth1.base object should be populated w/the default values for my provider, and then extend that w/my custom options?

If you don't have time to look into it, maybe you could nudge me in the right direction :)

Thanks for your awesome work in porting this to Angular2.

**Comment by ronzeidman** [comment]
Hi, thanks for the attempt at fixing the code.
Try using version 3.1.2 there was an issue with "extend" method that probably caused this degradation. I'll check it out

**Comment by ronzeidman** [comment]
I've reverted 3.2.0 changes, you can use 3.2.1 (it's the same as 3.1.2).
You can also try and test my attempt to fix this issue by using the library directly from github, I've replaced "extend" with "assign". I don't have a twitter "app" so I'll have to create one to test it myself so it might take a while.

**Comment by sunild** [comment]
Confirming this is working, thanks!

**Comment by ronzeidman** [comment]
@sunild You've confirmed it's working on 3.2.1 or on master?

**Comment by sunild** [comment]
This fix is working in 3.2.1 (and I assume master too, see below). I have a funny scenario which I cannot figure out, however, so please take this w/a grain of salt...

I've forked this repo and am successfully authenticating w/Twitter and Facebook but only when I install ng2-ui-auth from the local copy on disk (eg: `npm install ../ng2-ui-auth`).

If I try to use 3.2.1 from npm, I can confirm that this fix (for Twitter config values being null) is working.  However, when I use 3.2.1 from npm, I have another problem where (for both Twitter and Facebook) my server doesn't receive the necessary query params to finish the process (this is basically the other issue I reported, #31 ).

I'm at a loss as to explain why it's not working when I directly use the npm module, but works when I use my forked repo (w/no code changes).  

I am using angular-cli to build my project, and noticed it's "tree shaking" process (to make optimized builds for production) causes yet another issue when I use the minified version of ng2-ui-auth in my project.  At least one method from ng2-ui-auth gets omitted from my application bundle, and things are broken.

I'm assuming the weird issues I'm seeing are probably a result of angular-cli's build process. Sorry, this is a bit muddled 😕

**Comment by ronzeidman** [comment]
I've made changes in the master branch that I did not publish yet to npm (because I didn't thoroughly test it myself, I just tested basic functionality) so the fork probably have different source from the latest npm version, that's why I asked you if you've tested the "master" branch instead of the 3.2.1 npm version. The changes include assigning user-specific parameters in the authenticate function, so if I'm reading correctly that may be the issue.
As for tree-shaking, I don't think it's production-ready yet so I don't know what or how to debug it. I'm using rollup for bundling/minifing and it seems to give the best results (compared to webpack+gulp) with minimal configuration. If you find some other process that gives comparable results without "tree shaking" issues I'm open to hearing about it or merging a pull request.
