### ISSUE TITLE
Authorization fails for Google login  

### ISSUE THREAD

**Issue by ChamithaCalcey** [ronzeidman/ng2-ui-auth#34]
Hi ronzeidman,

A 404 error occurred with zone.js file while authenticating the user (POST request). Please refer to the attachments.

Thanks

![capture](https://cloud.githubusercontent.com/assets/20455632/17055357/e1e66e44-5029-11e6-95d2-f60f93fd64e0.PNG)

[WebClientFrontEnd.zip](https://github.com/ronzeidman/ng2-ui-auth/files/378162/WebClientFrontEnd.zip)

**Comment by ronzeidman** [comment]
The error says that there is no such route with the name auth/google in your server, the code you gave was client code. I guess your problem is that you didn't implement the server-side.
You can see a basic server-side example for basic login, google and twitter here: https://github.com/ronzeidman/ng2-ui-auth-example/blob/master/server/src/routes/auth.ts
and an example for various server-side implementation for everything and many languages here:
https://github.com/sahat/satellizer/tree/master/examples/server

**Comment by ChamithaCalcey** [comment]
Can you please explain how to implement the server side to my existing code. I'm new to Angular 2 and can you describe me the basic steps?

**Comment by ronzeidman** [comment]
The server-side is not about angular2 it's an implementation that runs in your server to save your user login info in your database. If you are using a serverless implementation (like firebase/horizon) you'll have to use a serverless authentication solution like auth0 (https://auth0.com/).
In what language is your server written? whats the database you are using?
