### ISSUE TITLE
Please implement refresh token

### ISSUE THREAD

**Issue by nigel-dewar** [ronzeidman/ng2-ui-auth#41]
Hi Ronz, 

When you get a chance, can you please implement Token Refresh on the jwtHttp class.

cheers.

**Comment by heinbez** [comment]
This may point you in the right direction. What I did was

```ts
jwtHttp.ts

	request(...) {
	    if(this._shared.tokenExpired()) {
	       return this._shared.refreshToken().flatMap(token => {
	       		if(typeof token === 'string') {
	       			// set the new token
	       			this._shared.setToken(token);
	       		}

	       		// retry the request
	       		return this.request(url, options)
	       })
	       .catch((err, res) => {
	       		// remove token if we failed to refresh
	       		this._shared.removeToken()

	       		// retry the request
	       		return this.request(url, options)
	       })
	    }

	    super.request(url, options).retryWhen((errors) => {
	        return Observable.timer(500)
	    })
	}
```

```ts
shared.ts

	refreshToken(): Observable<Response> {
    	var authHeader = new Headers()
    	authHeader.append(this.config.authHeader, (this.config.authToken + ' ' + this.getToken()))

        return this.http.get(this.config.refreshUrl, {
        	headers: authHeader
        }).map((res: Response) => {
        	return res.json().token
        })
    }
```

This was a quick and hacky way to do it.

**Comment by ronzeidman** [comment]
Crazy week, will probably implement it sometime next week. If someone is willing to "Pull request" I'd be happy to accept.

**Comment by ronzeidman** [comment]
Just committed something to my side-branch you are welcome to test (branch name "static-provider").

**Comment by royipressburger** [comment]
Isn't the right way to do that will be to create a secondary token and send it on the refresh request and not to send the actual auth token?

**Comment by ronzeidman** [comment]
There are several methods. A dedicated refresh token doesn't provide any additional security over just sending the outdated onc since it can be replaced with an actual token and provide access. The only additional information it gives is for how long you can use it. May be I'll add "refresh token key" and property to save it along the actual token where by default it will be the same as the original token...

**Comment by nigel-dewar** [comment]
Hi Ronz,

Thanks very much I will try this out. Sorry for late reply, I went away for weekend and just started new job at uni.

I will try this out today.

**Comment by nigel-dewar** [comment]
Hi Ron,

Im not perfectly sure how the refresh token is supposed to work. I will have a look at the another solution I was researching ‘IdentityServer’ with its js library called oidc.js and see how it works.

All I know is that when a user goes to make a call, there is a function that checks if token is expired, and if it is, it goes out and tries to get a new one.

Cheers

**Comment by ronzeidman** [comment]
After re-reading about it a bit there are two flows you might want to implement in order to refresh your token:
Unlimited (in time) refresh token - In this highly insecure way you receive a refresh token (and an initial access token) when you first log in, then you must save the refresh token in a secure location (cannot be done in the browser, that's why this method is used mostly on mobile devices) whenever you want to re-log-in just use the refresh token and get a new access token. The reason this is not just an unlimited ordinary access token is that the ordinary access token may contain user information that could change and if you just keep that it can never change.
Also in order to be able to revoke refresh token you have to store every refresh token id you've ever created and and when refreshing the token check if it exists (you shouldn't save only the revoked ones since you'd want the user to be able to choose which token he wishes to revoke).

Expired or old access token - you can exchange an old or expired access token with a new one so that if you are not idle in the application and the token you initially gave had an expiration date of 10 hours for example you could continue using it and get a new one. In the server-side when you want to refresh you can check when it was (or will) expired and if it's within a reasonable time (like 30 minutes) you can give the client a new one. This lets your client keep it's "session" open forever until he becomes idle for too long and then he will need to login again.

What do you want this library to implement?

**Comment by nigel-dewar** [comment]
Hi Ron.  The latter. Expired or old access token ,  is the one. The ability to renew a token within its set time frame if the app is not idle is the desired behavior. And if not then user must login again.

Thanks so much for taking a deep look at this.

Nige.


Sent from Samsung Mobile


-------- Original message --------
From: Ron Zeidman
Date:30/08/2016 20:06 (GMT+10:00)
To: ronzeidman/ng2-ui-auth
Cc: nigel-dewar , Author
Subject: Re: [ronzeidman/ng2-ui-auth] Please implement refresh token (#41)


After re-reading about it a bit there are two flows you might want to implement in order to refresh your token:
Unlimited (in time) refresh token - In this highly insecure way you receive a refresh token (and an initial access token) when you first log in, then you must save the refresh token in a secure location (cannot be done in the browser, that's why this method is used mostly on mobile devices) whenever you want to re-log-in just use the refresh token and get a new access token. The reason this is not just an unlimited ordinary access token is that the ordinary access token may contain user information that could change and if you just keep that it can never change.
Also in order to be able to revoke refresh token you have to store every refresh token id you've ever created and and when refreshing the token check if it exists (you shouldn't save only the revoked ones since you'd want the user to be able to choose which token he wishes to revoke).

Expired or old access token - you can exchange an old or expired access token with a new one so that if you are not idle in the application and the token you initially gave had an expiration date of 10 hours for example you could continue using it and get a new one. In the server-side when you want to refresh you can check when it was (or will) expired and if it's within a reasonable time (like 30 minutes) you can give the client a new one. This lets your client keep it's "session" open forever until he becomes idle for too long and then he will need to login again.

What do you want this library to implement?

-

**Comment by ronzeidman** [comment]
Does the side-branch work for you? should I merge it to the main branch?

**Comment by ronzeidman** [comment]
Added to version 3.2.3, if you need some extra features like the time before expiration to try and refresh the token open a different issue.
