### ISSUE TITLE
Pass additional parameters for different authentications

### ISSUE THREAD

**Issue by snowcxt** [ronzeidman/ng2-ui-auth#46]
Is there a way to pass additional parameters for different authentications? e.g.:

```javascript
// default
return this.auth.authenticate(provider)
```

```javascript
// authenticate with different parameters
return this.auth.authenticate(provider, {}, { state: 'different parameters' })
```

**Comment by snowcxt** [comment]
I got it just use function

**Comment by ronzeidman** [comment]
I didn't understand your second comment. Did you find a solution?

**Comment by snowcxt** [comment]
You can use function instead of hard code state: e.g.
```typescript
google: {
        clientId: GOOGLE_CLIENT_ID,
        state: () => {
          if (what ever) return 'abc';
          return 'efg';
        }
      }
```

**Comment by ronzeidman** [comment]
Yea, you can but it's probably harder since there are no variables passed to the state. You could however add another provider with `myGoogle: Object.assign({}, theGoogleProvider, { state: 'my new state' }` and use that whenever you need it.
Anyway seems like it became a non-issue for you so if there are no more people requiring this feature I will close the issue.
