### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jamesmcroft** [ronzeidman/ng2-ui-auth#48]
There needs to be more documentation on how to use this library as the libs themselves and the example/sample seem to be out of sync in terms of usage meaning that it's not clear on how everything ties together.

**Comment by ronzeidman** [comment]
You're right, I had plans to update the example for some time now... But it will take a while longer probably a couple of weeks since I'm still pretty busy...
In the meantime the server-side is fully demonstrated in the satellizer project: https://github.com/sahat/satellizer/tree/master/examples/server
Obtaining auth keys is also there:
https://github.com/sahat/satellizer#obtaining-oauth-keys
The ui-side usage is explained in the readme here and if you have a particular issue I can help here.

**Comment by ronzeidman** [comment]
I've updated my https://github.com/ronzeidman/ng2-ui-auth-example to the latest versions of everything, plus it is fully re-implemented to be more clear.
Please try it and tell me what you think.
Thanks.
