### ISSUE TITLE
Twitter login tries to open local route of '/auth/twitter' instead of their api.twitter.com page

### ISSUE THREAD

**Issue by elliottross23** [ronzeidman/ng2-ui-auth#55]
Whenever I call authenticate('twitter') it opens a popup window and tries to redirect to a local route of '/auth/twitter'. Is there some config I need to do for Twitter to work? I created an app on Twitter but am not sure where to connect it.

My Config file
```
import { CustomConfig } from 'ng2-ui-auth';

export class AuthConfig extends CustomConfig {
    defaultHeaders = {'Content-Type': 'application/json'};
    providers = {
    	google: {
    		clientId: '<replace me>'
    	},
    	facebook: {
    		clientId: '1675283336115039',
    		responseType: 'token'
    	}
    };
}
```

And then my call, where provider = 'twitter'
```
this.Auth.authenticate(provider).subscribe({
        error:(err: any) => {
        	console.log(err);
        },
        complete:() => {
        	console.log(this.Auth.getToken());
        	console.log(this.Auth.getPayload());
        }
    });
```

**Comment by ronzeidman** [comment]
Hi, 
this is a fork of the example a friend has made: https://github.com/MosheBiton/ng2-ui-auth-example
it contains twitter authentication implementation.
https://github.com/MosheBiton/ng2-ui-auth-example/blob/master/client/src/config.ts
https://github.com/MosheBiton/ng2-ui-auth-example/blob/master/server/src/auth.ts#L193
this is an example with a server-side implementation and it uses twitter's oauth1 implementation.
If you wish authorization instead of authentication add to the client `authorizationEndpoint: 'https://api.twitter.com/oauth/authorize'`
Since twitter uses OAuth 1.0a and not OAuth2 there is no "responseType: 'token'" you can use to skip the server-side so as far as I know, if you you have to use a server-side (unless you use solutions such as auth0 that does the server-side for you).
