### ISSUE TITLE
Add link to other social

### ISSUE THREAD

**Issue by speedfl** [ronzeidman/ng2-ui-auth#58]
Is it possible to link another social to a given profile ? 
Let's imagine I logged with facebook.
Then later I would like to associate a linkedin or twitter to my profile. Is there a way ?

**Comment by speedfl** [comment]
I am closing issue as we can handle it on server side if header is there and provider not already there  :)

**Comment by ronzeidman** [comment]
As you can see in the example, you can use the "link" method to do that: https://github.com/ronzeidman/ng2-ui-auth-example/blob/master/client/src/components/main.component.ts#L51
It's actually the same as authenticate and everything should be implemented server-side like you said:
you can see an example implementation here:
https://github.com/ronzeidman/ng2-ui-auth-example/blob/master/server/src/auth.ts#L119
"Step 3.a." covers the linking logic since the user is already signed in.
